# render.yaml — configuración de despliegue en Render

services:
  - type: web
    name: osdiaples
    env: docker
    plan: free
    region: oregon
    dockerCommand: ""
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
